# Site settings
title: Timby
email: ryan@circle.co.ke
description: Timby
baseurl: "/timby-pages" # the subpath of your site, e.g. /blog/
# url: "http://www.dominos.co.ke" # the base hostname & protocol for your site
twitter_username: circlekenya
github_username:  ryanhbowman

# Build settings
markdown: kramdown

# Sass stuff
sass:
  style: compressed
